import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    name: "OĞUZHAN MENEMENCİ2",
    town: "kadikoy",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "78 KBU 2023",
    location: [41.216693, 31.955387],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "SEMİH ŞAHİN",
    town: "beylikduzu",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "19 SMH 19",
    location: [40.54994, 34.954166],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "AHMET MEHMET1",
    town: "esenyurt",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "34 IST 34",
    location: [40.016297, 28.985442],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI2",
    town: "esenyurt",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "UMUT OZAN3",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "06 SVP 54",
    location: [51.589076, -3.329799],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "arif burak4",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "07 ARF 3169",
    location: [36.85997, 30.599469],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI5",
    town: "esenyurt",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "OĞUZHAN MENEMENCİ",
    town: "kadikoy",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "78 KBU 2023",
    location: [41.216693, 32.655387],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "SEMİH ŞAHİN",
    town: "beylikduzu",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "19 SMH 19",
    location: [40.54994, 34.954166],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "AHMET MEHMET6",
    town: "esenyurt",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "34 IST 34",
    location: [41.016297, 28.985442],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI",
    town: "esenyurt",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "UMUT OZAN",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "06 SVP 54",
    location: [51.589076, -3.329799],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "arif burak",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "07 ARF 3169",
    location: [36.85997, 30.599469],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "OĞUZHAN MENEMENCİ",
    town: "kadikoy",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "78 KBU 2023",
    location: [41.216693, 32.605387],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "SEMİH ŞAHİN",
    town: "beylikduzu",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "19 SMH 19",
    location: [40.54994, 34.954166],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "AHMET MEHMET",
    town: "esenyurt",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "34 IST 34",
    location: [41.016297, 28.985442],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI",
    town: "esenyurt",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "UMUT OZAN",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "06 SVP 54",
    location: [51.589076, -3.329799],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "arif burak",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "07 ARF 3169",
    location: [36.85997, 30.599469],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "OĞUZHAN MENEMENCİ2",
    town: "kadikoy",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "78 KBU 2023",
    location: [41.216693, 31.955387],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "SEMİH ŞAHİN",
    town: "beylikduzu",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "19 SMH 19",
    location: [40.54994, 34.954166],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "AHMET MEHMET1",
    town: "esenyurt",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "34 IST 34",
    location: [40.016297, 28.985442],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI2",
    town: "esenyurt",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "UMUT OZAN3",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "06 SVP 54",
    location: [51.589076, -3.329799],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "arif burak4",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "07 ARF 3169",
    location: [36.85997, 30.599469],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI5",
    town: "esenyurt",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "OĞUZHAN MENEMENCİ",
    town: "kadikoy",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "78 KBU 2023",
    location: [41.216693, 32.655387],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "SEMİH ŞAHİN",
    town: "beylikduzu",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "19 SMH 19",
    location: [40.54994, 34.954166],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "AHMET MEHMET6",
    town: "esenyurt",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "34 IST 34",
    location: [41.016297, 28.985442],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI",
    town: "esenyurt",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "UMUT OZAN",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "06 SVP 54",
    location: [51.589076, -3.329799],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "arif burak",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "07 ARF 3169",
    location: [36.85997, 30.599469],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "OĞUZHAN MENEMENCİ",
    town: "kadikoy",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "78 KBU 2023",
    location: [41.216693, 32.605387],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "SEMİH ŞAHİN",
    town: "beylikduzu",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "19 SMH 19",
    location: [40.54994, 34.954166],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "AHMET MEHMET",
    town: "esenyurt",
    vehicle: "servis",
    phone: "0(000) 000 00 00",
    plate: "34 IST 34",
    location: [41.016297, 28.985442],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI",
    town: "esenyurt",
    vehicle: "otobus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "UMUT OZAN",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "06 SVP 54",
    location: [51.589076, -3.329799],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "arif burak",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "07 ARF 3169",
    location: [36.85997, 30.599469],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
  {
    name: "ERAY KARAKAŞLI",
    town: "esenyurt",
    vehicle: "minibus",
    phone: "0(000) 000 00 00",
    plate: "34 FB 1907",
    location: [40.990493, 29.029002],
    passengers: [
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
      "Dilruba",
      "Gizem",
      "Ayşe",
      "Fatma",
      "Hayriye",
      "Ahmet",
      "Mehmet",
      "Mustafa",
      "Mami",
      "Aslı",
    ],
  },
];

export const userSlice = createSlice({
  name: "user",
  initialState,
  reducers: {
    setUser: (state, action) => {
      return action.payload;
    },
  },
});

export const { setLocation } = userSlice.actions;

export default userSlice.reducer;
